spring:
  datasource:
    url: jdbc:mysql://localhost:3306/big_event
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: edg127117

  data:
    redis:
      host: 192.168.27.136
      port: 6379
      password: "123456"
      database: 0
      timeout: 30000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          shutdown-timeout: 10000ms

mybatis:
  configuration:
    map-underscore-to-camel-case: true
